### ISSUE TITLE
secure MQTT pub?

### ISSUE THREAD

**Issue by holgerkoch** [elementzonline/SIM800_MQTT#14]
Hi,

thank you very much for your great work. It works really good for me.
Do you have plan to secure the communication between the arduino and the MQTT server with TLS?

Best regards

Holger Koch

**Comment by elementzonline** [comment]
The TLS encryption is having some overhead, We don't have any plan for supporting TLS with this library in the near future

**Comment by pntuan** [comment]
Hi,

Thank you so much. This library work well but need more secure. What about user/password for pub/sub topic ?

Best regards,
TuanPN
