### ISSUE TITLE
doesn't work with broker.hivemq.com broker

### ISSUE THREAD

**Issue by Anubhav1001** [elementzonline/SIM800_MQTT#18]
Dear Elementzonline, we used your latest code to connect to the MQTT broker "broker.hivemq.com" the code connects however immediately after connecting it gives "disconnecting mqtt" error.

This code works with aREST server "45.55.196.201" but some how disconnects everytime a standard MQTT broker server line "broker.hivemq.com" is used.

Please suggest what might be the issue?

**Comment by kamrankamrani** [comment]
its too late but for others
use port 1883 for this broker and i working now with no problem
