### ISSUE TITLE
Question : AT+CIPSEND GSM

### ISSUE THREAD

**Issue by sivasankars** [elementzonline/SIM800_MQTT#20]
Without AT+CIPSEND can we send data to GSM ? I didn't find AT+CIPSEND on your code ?

Thanks,
Siva

**Comment by elementzonline** [comment]
Its working in TCP transparent mode.

**Comment by krpagar** [comment]
Same question ! Could you plz share where it goes to transparent mode? Which command is there?

**Comment by krpagar** [comment]
By the way, nice code and efforts ! I Appreciate.
