### ISSUE TITLE
[QUESTION] ESP8266 compatibility

### ISSUE THREAD

**Issue by Franciscopcosta** [elementzonline/SIM800_MQTT#25]
How can i adapt it to work with ESP8266?

**Comment by kristofferJr** [comment]
I'm asking the same question

**Comment by elementzonline** [comment]
Yes, there are some changes to be done in AT commands, otherwise should be working fine. But writing code directly to support MQTT in ESP8266 is the straightforward approach.

**Comment by agozie** [comment]
For all those getting stuck at `MQTT.MessageFlag = true` when using software serial, ESP8266 or other platforms, change `GSM_MQTT::processing` in `GSM_MQTT.cpp` to
```cpp 
void GSM_MQTT::processing(void)
{
 if (TCP_Flag == false)
  {
    MQTT_Flag = false;
    _tcpInit();
  }
  _ping();

  //**************new code*****************
  unsigned long t = millis();
  //add long waitPeriod = 0; somewhere at the beginning of the file
  if (t - waitPeriod > 1000L) 
  {
    waitPeriod = t;
    serialEvent(); //call serialEvent every second
  }
  //*****************************************

}

**Comment by elementzonline** [comment]
Closing the issue as ESP8266 is offtopic and not intended as the target for this library
