### ISSUE TITLE
Problem with autoconnect

### ISSUE THREAD

**Issue by marsaldia** [elementzonline/SIM800_MQTT#27]
Hello!

In some random cases, I see that the connection is closed, but the MQTT.TCP_Flag is still True and the mqtt.available is true. I think that for this reason, the auto-connect function is not called again until the arduino is manually restarted.

As I tell I do not know exactly when it is happen, but if someone likes to reproduce the error, it is possible to reproduce the error cutting off the power of the SIM900 and turn it on again.

Any help is really appreciated.

**Comment by marcosdepo** [comment]
I have the same problem, after several hours or days, conection fails but don't reconect.
Have you got any solution?
Thanks.
