### ISSUE TITLE
Can't publish and subscribe

### ISSUE THREAD

**Issue by Franciscopcosta** [elementzonline/SIM800_MQTT#31]
I get the message:

AT+CREG?

+CREG: 0,5

OK
AT+CIPMUX=0

OK
AT+CIPMODE=1

OK
AT+CGATT?

+CGATT: 1

OK
AT+CIPSTATUS

OK

STATE: IP INITIAL
AT+CSTT="wm"

OK
AT+CIPSTATUS

OK

STATE: IP START
AT+CIICR

OK
AT+CIPSTATUS

OK

STATE: IP GPRSACT
AT+CIFSR

xxx.xxx.x.x (ip address)
AT+CIPSTATUS

OK

STATE: IP STATUS
AT+CIPSTART="TCP","_my_broker_ip_","1883"

OK

CONNECT
MQTT.TCP_Flag = True

But i cant publish and subscribe.
`if (MQTT.available())
  {
    Serial.println("MQTT available...");
  }`
also this is not working, i never get the message "MQTT available..." on my serial.
Please can anyone help me?
(SIM800L with ESP32 via HardwareSerial UART2)

**Comment by fdeizaguirre** [comment]
Dear @Franciscopcosta I'm having the same problem, did   you made any improvement?

**Comment by marcosdepo** [comment]
Serial pins Rx and Tx work with SIM800 module.
This library uses software serial "mySerial"
Change Serial.println("MQTT available..."); with mySerial.println("MQTT available...");
Conect an external usb/serial driver to software serial pins, it works for me.
