### ISSUE TITLE
Help in Publish continuous data 

### ISSUE THREAD

**Issue by krpagar** [elementzonline/SIM800_MQTT#33]
Thanks for making library available for us !

I started with the library examples. I am able to connect to Adaruits.io but not able to publish data continuously... In fact i don't know where to and how add publish routine.. if could any sample simple code which sending data to broker then it would be very helpful for me.

**Comment by elementzonline** [comment]
https://github.com/elementzonline/SIM800_MQTT/blob/master/GSM_MQTT_Arduino_Publish/GSM_MQTT_Arduino_Publish.ino
