### ISSUE TITLE
inchar == 13 what is it mean

### ISSUE THREAD

**Issue by kamrankamrani** [elementzonline/SIM800_MQTT#35]
hi, this is a great library and thanks for sharing this
I have a problem whit hivemq broker. when i connect publish or any thing, after a time about 10 seconds or 15 seconds, broker send 0x0D or same 0x00001101 binary format data. in library there is an else if called for this type data and nothing write in it.
what is this data means? and why broker send it every time after particular time?
best regards , kamran

**Comment by elementzonline** [comment]
This is the ping response that send from the broker for the ping message. You may go through the MQTT spec for knowing the internals of the protocol.
