### ISSUE TITLE
KeepAlive not attempting to reconnect

### ISSUE THREAD

**Issue by pratikidea** [elementzonline/SIM800_MQTT#36]
If somehow gsm signal goes keep alive not reattempting to connect tcp and mqtt. It's stuck in tcpflag true state. Please advice.

Arduino nano
Sim800c

**Comment by marcosdepo** [comment]
I'm trying to refresh
`_tcpStatus = sendATreply("AT+CIPSTATUS\r\n", "STATE", 4000); `
inside
`GSM_MQTT::processing()`
after some time TCP connection falls down and `AT+CIPSTATUS` responses IP INITIAL

**Comment by marcosdepo** [comment]
check
https://github.com/elementzonline/SIM800_MQTT/pull/37#issue-368196204

**Comment by elementzonline** [comment]
Hi @marcosdepo , Thanks for the update. 

@pratikidea, Please confirm whether the issue got solved using these changes.
