### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by aria-joozani** [elementzonline/SIM800_MQTT#43]
hi I get this erro when i compile the for arduino uno 
In function 'void serialEvent()':
error: 'class GSM_MQTT' has no member named 'MQTT_flag'; did you mean 'MQTT_Flag'?
             MQTT.MQTT_flag = false;
                  ^~~~~~~~~
                  MQTT_Flag
should I change the MQTT_flag to MQTT_Flag ??

**Comment by raleortiz** [comment]
GSM_MQTT.cpp:686:25: error: '_delay_us' was not declared in this scope
             _delay_us(10);

**Comment by yashwanthkotla** [comment]
Modify MQTT_flag to MQTT_Flag

**Comment by elementzonline** [comment]
Pull request #45 merged
