### ISSUE TITLE
Worried about millis() timer overflow?

### ISSUE THREAD

**Issue by tinamore** [elementzonline/SIM800_MQTT#9]
Hi. 
`void GSM_MQTT::_ping(void)
{

  if (pingFlag == true)
  {
    unsigned long currentMillis = millis();
    if ((currentMillis - _PingPrevMillis ) >= _KeepAliveTimeOut \* 1000)
    {
      // save the last time you blinked the LED
      _PingPrevMillis = currentMillis;
      Serial.print(char(PINGREQ \* 16));
      _sendLength(0);
    }
  }
}`

when millis() over 49days and millis() = 0 again ?

**Comment by nithinkurian** [comment]
thanks for your concern this issue is rectified
